# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18cea61189785618ce11e2378e5951d5e89162a3f2fc2bc9f468dfe62bfa5e23b7fd4f609dea8c9c41978abc981fb5cb7caa9921623bd85ac9cbe4e3346476d0

test:
  secret_key_base: bfe69bfd1a5d31aba4c1ded6b1e791ce2daf1fbf455d410f83dc4ef39cb399dda1a82c9431f06c7596939a4d019126460134e2204df7a0df7929fbe7a76eddec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
